version: '3'
services:
  web:
    build: .
    container_name: flask_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app

  worker:
    build: .
    container_name: celery_worker
    command: celery -A celery_app.celery_config.app worker --loglevel=info -P solo
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
